name: Build

on:
  push:
    branches: [ main]

  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        units: [2000, 4000, 6000, 8000, 10000, 12000, 14000, 16000, 18000, 2000]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  17

      - name: Build
        run: |
          echo  ${{ matrix.units }}
          unzip ${{ matrix.units }}.zip
          mkdir layer_0
          mv  ${{ matrix.units }}/layer_0/* layer_0
          mvx kbuild.gradle.kts layer_0/module_d/build.gradle.kts
          ./gradlew tasks
          ls
          cd layer_0
          ls
          cd module_d
          ls
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_KEY }}
